version: '3'

services:
  api:
    container_name: api
    image: kameleoon-trial-task-img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
